name: Cypress Tests

on: [push]


jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests



      - name: Cypress run 
        run: |
          node_modules/.bin/cypress run --env Auth=${{secrets.AUTHORIZATION}}
          echo "$Auth"
        with: 
          record: true
        env: 
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{secrets.GIHUB_TOKEN}}
