name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests

      - name: Publish package
        run: |
          sed -i 's/${AUTHORIZATION}/${{ env.AUTHORIZATION }}/g' cypress.env.json
          npm publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          AUTHORIZATION: ${{secrets.AUTHORIZATION}}

      - name: Cypress run 

        uses: cypress-io/github-action@v2
        with: 
          record: true
        env: 
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{secrets.GIHUB_TOKEN}}
          AUTHORIZATION: ${{secrets.AUTHORIZATION}}

